version: '3'

services:
  nginx:
    image: nginx:1.25.4-alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - php-fpm
    restart: on-failure

  php-fpm:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www
    restart: on-failure
